//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_car_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string passwordHash { get; set; }
    }
}
