//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_car_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int id { get; set; }
        public string description { get; set; }
        public string imageUrl { get; set; }
        public Nullable<decimal> pricePerDay { get; set; }
        public Nullable<int> modelId { get; set; }
        public string Brand { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
